#ifdef __cplusplus
#include <QByteArray>
#include <QDir>
#include <QMainWindow>
#include <QObject>
#include <QQuickItem>
#include <QSharedDataPointer>
#include <QString>
#include <QString>
#include <QWidget>
#include <QtEndian>
#include <bitset>
#include <cstring>
#include <ctime>
#include <fstream>
#include <iostream>
#include <vector>
#include <windows.h>
#include <thread>
#endif
